volumes:
  learou_local_redis_data: {}
  production_postgres_data: {}
  production_postgres_data_backups: {}
  production_django_media: {}
  
  production_redis_data: {}
services:
  tailwind:
    build:
      context: .
      dockerfile: ./compose/prod/tailwind/Dockerfile
    image: learou_local_tailwind
    container_name: learou_local_tailwind
    volumes:
      - .:/app:z

  redis:
    image: docker.io/redis:6
    container_name: learou_local_redis
    volumes:
      - learou_local_redis_data:/data

  postgres:
    build:
      context: .
      dockerfile: ./compose/prod/postgres/Dockerfile
    image: learoy_postgres_prod
    volumes:
      - production_postgres_data:/var/lib/postgresql/data
      - production_postgres_data_backups:/backups
    env_file:
      - ./.envs/.production/.postgres

  django: &django
    build:
      context: .
      dockerfile: ./compose/prod/django/Dockerfile
    image: learou_local_django
    container_name: learou_local_django
    depends_on:
      - redis
      - postgres
    volumes:
      - .:/app:z
    env_file:
      ./.envs/.production/.django
    ports:
      - '5000:5000'
    command: /start

  nginx:
    build:
      context: .
      dockerfile: ./compose/prod/nginx/Dockerfile
    image: learou_production_nginx
    depends_on:
      - django
    volumes:
      - production_django_media:/usr/share/nginx/media:ro
