# Generated by Django 5.2.3 on 2025-07-02 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='model_custom_name',
            field=models.CharField(blank=True, verbose_name='Model custom name'),
        ),
        migrations.AddField(
            model_name='bibliographytype',
            name='model_custom_name',
            field=models.CharField(blank=True, verbose_name='Model custom name'),
        ),
        migrations.AddField(
            model_name='linktype',
            name='model_custom_name',
            field=models.CharField(blank=True, verbose_name='Model custom name'),
        ),
        migrations.AddField(
            model_name='projectstatus',
            name='model_custom_name',
            field=models.CharField(blank=True, verbose_name='Model custom name'),
        ),
        migrations.AddField(
            model_name='projecttype',
            name='model_custom_name',
            field=models.CharField(blank=True, verbose_name='Model custom name'),
        ),
        migrations.AddField(
            model_name='taskstatus',
            name='model_custom_name',
            field=models.CharField(blank=True, verbose_name='Model custom name'),
        ),
        migrations.AddField(
            model_name='tasktype',
            name='model_custom_name',
            field=models.CharField(blank=True, verbose_name='Model custom name'),
        ),
        migrations.AlterField(
            model_name='author',
            name='review',
            field=models.ManyToManyField(blank=True, to='app.review', verbose_name='Review'),
        ),
        migrations.AlterField(
            model_name='bibliography',
            name='authors',
            field=models.ManyToManyField(blank=True, to='app.author', verbose_name='Authors'),
        ),
        migrations.AlterField(
            model_name='bibliography',
            name='link',
            field=models.ManyToManyField(blank=True, to='app.link', verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='bibliography',
            name='review',
            field=models.ManyToManyField(blank=True, to='app.review', verbose_name='Review'),
        ),
        migrations.AlterField(
            model_name='cheatsheet',
            name='bibliography',
            field=models.ManyToManyField(blank=True, to='app.bibliography', verbose_name='Bibliography'),
        ),
        migrations.AlterField(
            model_name='cheatsheet',
            name='link',
            field=models.ManyToManyField(blank=True, to='app.link', verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='cheatsheet',
            name='review',
            field=models.ManyToManyField(blank=True, to='app.review', verbose_name='Review'),
        ),
        migrations.AlterField(
            model_name='diary',
            name='bibliography',
            field=models.ManyToManyField(blank=True, to='app.bibliography', verbose_name='Bibliography'),
        ),
        migrations.AlterField(
            model_name='diary',
            name='link',
            field=models.ManyToManyField(blank=True, to='app.link', verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='diary',
            name='project',
            field=models.ManyToManyField(blank=True, to='app.project', verbose_name='Project'),
        ),
        migrations.AlterField(
            model_name='diary',
            name='review',
            field=models.ManyToManyField(blank=True, to='app.review', verbose_name='Review'),
        ),
        migrations.AlterField(
            model_name='diary',
            name='tasks',
            field=models.ManyToManyField(blank=True, to='app.task', verbose_name='Task'),
        ),
        migrations.AlterField(
            model_name='diaryentry',
            name='bibliography',
            field=models.ManyToManyField(blank=True, to='app.bibliography', verbose_name='Bibliography'),
        ),
        migrations.AlterField(
            model_name='diaryentry',
            name='diary',
            field=models.ManyToManyField(blank=True, to='app.diary', verbose_name='Diary'),
        ),
        migrations.AlterField(
            model_name='diaryentry',
            name='link',
            field=models.ManyToManyField(blank=True, to='app.link', verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='diaryentry',
            name='project',
            field=models.ManyToManyField(blank=True, to='app.project', verbose_name='Project'),
        ),
        migrations.AlterField(
            model_name='diaryentry',
            name='review',
            field=models.ManyToManyField(blank=True, to='app.review', verbose_name='Review'),
        ),
        migrations.AlterField(
            model_name='diaryentry',
            name='tasks',
            field=models.ManyToManyField(blank=True, to='app.task', verbose_name='Task'),
        ),
        migrations.AlterField(
            model_name='project',
            name='bibliography',
            field=models.ManyToManyField(blank=True, to='app.bibliography', verbose_name='Bibliography'),
        ),
        migrations.AlterField(
            model_name='project',
            name='link',
            field=models.ManyToManyField(blank=True, to='app.link', verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_status',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app.projectstatus', verbose_name='Project Status'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app.projecttype', verbose_name='Project Type'),
        ),
        migrations.AlterField(
            model_name='project',
            name='review',
            field=models.ManyToManyField(blank=True, to='app.review', verbose_name='Review'),
        ),
        migrations.AlterField(
            model_name='project',
            name='tasks',
            field=models.ManyToManyField(blank=True, to='app.task', verbose_name='Task'),
        ),
        migrations.AlterField(
            model_name='technology',
            name='bibliography',
            field=models.ManyToManyField(blank=True, to='app.bibliography', verbose_name='Bibliography'),
        ),
        migrations.AlterField(
            model_name='technology',
            name='cheat_sheet',
            field=models.ManyToManyField(blank=True, to='app.cheatsheet', verbose_name='Cheat Sheet'),
        ),
        migrations.AlterField(
            model_name='technology',
            name='link',
            field=models.ManyToManyField(blank=True, to='app.link', verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='technology',
            name='review',
            field=models.ManyToManyField(blank=True, to='app.review', verbose_name='Review'),
        ),
    ]
