# Generated by Django 5.2.3 on 2025-07-02 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_author_model_custom_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bibliography',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='bibliography',
            name='model_custom_name',
            field=models.CharField(blank=True, verbose_name='Model custom name'),
        ),
        migrations.AddField(
            model_name='cheatsheet',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='cheatsheet',
            name='model_custom_name',
            field=models.CharField(blank=True, verbose_name='Model custom name'),
        ),
        migrations.AddField(
            model_name='diary',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='diary',
            name='model_custom_name',
            field=models.CharField(blank=True, verbose_name='Model custom name'),
        ),
        migrations.AddField(
            model_name='diaryentry',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='diaryentry',
            name='model_custom_name',
            field=models.CharField(blank=True, verbose_name='Model custom name'),
        ),
        migrations.AddField(
            model_name='link',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='link',
            name='model_custom_name',
            field=models.CharField(blank=True, verbose_name='Model custom name'),
        ),
        migrations.AddField(
            model_name='project',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='project',
            name='model_custom_name',
            field=models.CharField(blank=True, verbose_name='Model custom name'),
        ),
        migrations.AddField(
            model_name='review',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='review',
            name='model_custom_name',
            field=models.CharField(blank=True, verbose_name='Model custom name'),
        ),
        migrations.AddField(
            model_name='task',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='task',
            name='model_custom_name',
            field=models.CharField(blank=True, verbose_name='Model custom name'),
        ),
        migrations.AddField(
            model_name='technology',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='technology',
            name='model_custom_name',
            field=models.CharField(blank=True, verbose_name='Model custom name'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.projectstatus', verbose_name='Project Status'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.projecttype', verbose_name='Project Type'),
        ),
    ]
