# Generated by Django 5.2.3 on 2025-07-02 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_custommodelnamecollection_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='custommodelnamecollection',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('is_active',), name='unique_active_value'),
        ),
    ]
